### ISSUE TITLE
Method II: Setting Up a Conda Environment - fails with "ModuleNotFoundError: No module named 'notebook.nbextensions'"

### ISSUE THREAD

**Issue by expectopatronum** [groupmm/libsoni#8]
Hi,

I have been trying to install the package using the provided yml file as described in "Method II: Setting Up a Conda Environment" but I receive an error:

```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... Traceback (most recent call last):
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 6, in <module>
    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 10, in <module>
    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 12, in <module>
    from ._compat.nbextensions import BaseNBExtensionApp
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/_compat/nbextensions.py", line 35, in <module>
    from notebook.nbextensions import (
ModuleNotFoundError: No module named 'notebook.nbextensions'

Traceback (most recent call last):
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 6, in <module>
    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 10, in <module>
    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 12, in <module>
    from ._compat.nbextensions import BaseNBExtensionApp
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/_compat/nbextensions.py", line 35, in <module>
    from notebook.nbextensions import (
ModuleNotFoundError: No module named 'notebook.nbextensions'

Traceback (most recent call last):
  File "/home/verena/miniconda3/envs/libsoni/bin/jupyter-nbextensions_configurator", line 6, in <module>
    from jupyter_nbextensions_configurator.application import main
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_nbextensions_configurator/__init__.py", line 17, in <module>
    from notebook import version_info as nb_version_info
ImportError: cannot import name 'version_info' from 'notebook' (/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/notebook/__init__.py)

Traceback (most recent call last):
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 6, in <module>
    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 10, in <module>
    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/verena/miniconda3/envs/libsoni/bin/jupyter-contrib-nbextension", line 6, in <module>
    from jupyter_contrib_nbextensions.application import main
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_nbextensions/application.py", line 7, in <module>
    from jupyter_contrib_core.notebook_compat.nbextensions import ArgumentConflict
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 12, in <module>
    from ._compat.nbextensions import BaseNBExtensionApp
  File "/home/verena/miniconda3/envs/libsoni/lib/python3.8/site-packages/jupyter_contrib_core/notebook_compat/_compat/nbextensions.py", line 35, in <module>
    from notebook.nbextensions import (
ModuleNotFoundError: No module named 'notebook.nbextensions'



    Installed package of scikit-learn can be accelerated using scikit-learn-intelex.
    More details are available here: https://intel.github.io/scikit-learn-intelex

    For example:

        $ conda install scikit-learn-intelex
        $ python -m sklearnex my_application.py

    

done
Rolling back transaction: ...working... done
```

I was able to install the package without any problems using "Method I" but I wanted to let you know in case the yml file is missing some requirements or there is some extra step I need to run on my system. Please let me know if you need any more information from me!

Best regards
Verena

**Comment by yiitozer** [comment]
Thank you very much for pointing out this problem! We have found that the jupyter_contrib_nbextensions is not mandatory for libsoni, please see also https://github.com/groupmm/libsoni/commit/abefb9c6327f4fba6716089f5b18d68149619208
